AC_DEFUN([SPREAD_CHECKS],[	

AC_REQUIRE([AC_PROG_CC])
AC_REQUIRE([AC_PROG_LN_S])
AC_REQUIRE([AC_PROG_RANLIB])

AC_DEFINE(UNDEF_THREADS_HACK,,[ ])

SPREAD_HEADER_CHECKS
SPREAD_TYPE_CHECKS
SPREAD_FUNCTION_CHECKS
])